// Code generated by hive. DO NOT EDIT.

package rpc

import (
	"fmt"
	"github.com/benka-me/laruche-server/go-pkg/larsrv"
	"github.com/benka-me/users/go-pkg/users"
	"google.golang.org/grpc"
	"strconv"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = fmt.Sprintf("")
var _ = strconv.FormatInt(int64(0), 10)

type Clients struct {
	UsersGateway  users.UsersClient
	LarsrvGateway larsrv.LarsrvClient
}

const server = "api.laruche.services:8080"

func InitClients(options ...grpc.DialOption) Clients {

	gateway, err := grpc.Dial(server, grpc.WithInsecure())
	if err != nil {
		panic("Cannot dial")
	}
	return Clients{
		UsersGateway:  users.NewUsersClient(gateway),
		LarsrvGateway: larsrv.NewLarsrvClient(gateway),
	}
}
